
include: package:austerity/analysis_options.yaml

linter:
  rules:

analyzer: 
  errors:
    diagnostic_describe_all_properties: ignore
    dead_null_aware_expression: error
    invalid_null_aware_operator: error
 
