name: treeview
description: "A new Flutter project."

version: 0.1.0-beta

environment:
  sdk: '>=3.2.3 <4.0.0'


dependencies:
  cupertino_icons: ^1.0.2
  flutter:
    sdk: flutter

dev_dependencies:
  austerity: ^1.1.0
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
