name: CI

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: ${{ vars.FLUTTER_VERSION }}
          channel: "stable"
          cache: true
          cache-key: "flutter-:os:-:channel:-:version:-:arch:-:hash:"
          architecture: x64

      - name: Get Dependencies
        run: flutter pub get

      - name: Analyze
        run: dart analyze --no-fatal-warnings

      - name: Check Formatting
        run: dart format lib test --set-exit-if-changed

      - name: Run Tests
        run: flutter test --coverage

      - name: Check Test Coverage
        uses: VeryGoodOpenSource/very_good_coverage@v2
        with:
          path: 'coverage/lcov.info'
          min_coverage: 100

      - name: Create Coverage JSON
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        run: |
          echo '{"coverage": 100}' > coverage/coverage.json

      - name: Generate Coverage Badge
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        uses: jaywcjlove/coverage-badges-cli@main
        with:
          source: coverage/coverage.json
          output: coverage_badge.svg

      - name: Commit Coverage Badge
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add coverage_badge.svg
          git commit -m "docs: update coverage badge" || echo "No changes to commit"
          git push